name: Actualizar Cartelera Diaria

on:
  schedule:
    - cron: '30 4 * * *' # Se ejecuta todos los días a las 4:30 AM UTC
  workflow_dispatch: # Permite ejecutarlo de forma manual cuando quieras desde la pestaña Actions

jobs:
  sincronizar:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install pandas gspread oauth2client requests beautifulsoup4

      - name: Restaurar credenciales desde el secreto
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > credenciales.json

      - name: Ejecutar script de partidos
        run: |
          python3 app.py
